POST http://localhost:3030/books
Content-Type: application/json

{
    "name" : "nnn nnn",
    "author": "nnn"
}

###

GET http://localhost:3030/books
Content-Type: application/json

###

GET http://localhost:3030/books/1
Content-Type: application/json

###

PUT  http://localhost:3030/books/1
Content-Type: application/json

{
    "name" : "test 1222",
    "author": "2222"
}

###